DETECT_VIRTUAL_MACHINE = ("vm", "vbox", "sandbox", "agent.pyw", "analyzer.py")
SNIFFER = ("sandbox", "wireshark", "procexec", "sniffer", "debugging", "superantispyware", "bopup observer")
file = open("autoruns_paths.txt", 'r')
autoruns_paths = file.readlines()
PATH_TO_APP_INFO = "CurrentVersion\\\\Uninstall"
EXECUTABLE_FILES_EXTENTIONS = "(\.exe|\.dll|\.bat|\.vbs|\.pyc|\.py|\.lnk|\.cmd)"
BACKGROUND_REG_PATH = "Control Panel\\\\Desktop"
OFFICE_FILE_EXTENTIONS = "(\.doc|\.docm|\.docx|\.pdf|\.ppt|\.ppts|\.pptx|\.xlm|\.xlsm)"
STARTUP_FOLDER_PATH = "AppData\\\\Roaming\\\\Microsoft\\\\Windows\\\\Start Menu\\\\Programs\\\\Startup"
